import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((127.0.0.1 , 80))
s.listen(1)
print("server is listening....")
client, addr = s.accept()
print(f"connected by {addr}")
client.send(b"wellcome client")
data = client.recv(1024)
print("received:", data.decode())
client.close()
s.close()
